config/routes.rb
Rails.application.routes.draw do
  resources :videos
  resources :clients do
    member do
      get 'camcorder'
    end
  end
  root 'application#index'

end

app/models/client.rb
class Client < ActiveRecord::Base
  has_one :video
  paginates_per 10

  validates :first_name, :last_name, :email, presence: true
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
end

app/models/video.rb
class Video < ActiveRecord::Base
  belongs_to :client
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def index
    redirect_to clients_path
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all.order('created_at DESC').page params[:page]
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    # client_params = ActionController::Parameters.new(params)
    # client_params = client_params.permit(:first_name, :last_name, :email)
    @client = Client.new(params[:client])

    respond_to do |format|
      if @client.save
        format.html { redirect_to action: :new, notice: 'Client was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def camcorder

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:name, :email)
    end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]

  # GET /videos
  # GET /videos.json
  def index
    # @videos = Video.all
    @clients = Client.includes(:video)
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render json: @video.as_json }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params.require(:video).permit(:url, :client_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/clients/_form.html.erb
<%= form_for(@client) do |f| %>
  <% if @client.errors.any? %>
    <div id="error_explanation">
      <% @client.errors.full_messages.each do |message| %>
        <span class="error-message"><%= message %></span>
      <% end %>
    </div>
  <% end %>


  <div class="row">
    <div class="col-md-6">
      <%= f.text_field :first_name, :placeholder => "First name *" %>
    </div>
    <div class="col-md-6">
      <%= f.text_field :last_name, :placeholder => "Last name *" %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <%= f.email_field :email, :placeholder => "E-mail *" %>
    </div>
  </div>
<!--   <div class="row">
    <div class="col-md-12">
      <%= f.email_field :email, :placeholder => "Confirm E-mail *" %>
    </div>
  </div> -->

  <div class="actions">
    <%= f.submit (action_name=="new" ? "Submit" : "Update") %>
  </div>
<% end %>

app/views/clients/camcorder.html.erb
<div class="content-wrapper video">
  <object id="camcorder" width="640px" height="360px"
    codebase="http://fpdownload.macromedia.com/get/flashplayer/current/swflash.cab">
    <param name="movie" value="/red5recorder.swf" />
    <param name="quality" value="high" />
    <param name="bgcolor" value="#869ca7" />
    <param name="allowScriptAccess" value="sameDomain" />
    <embed src="/red5recorder.swf" quality="high" bgcolor="#869ca7"
      width="640" height="360" name="red5recorder" align="middle"
      play="true"
      loop="false"
      allowScriptAccess="sameDomain"
      type="application/x-shockwave-flash"
      pluginspage="http://www.adobe.com/go/getflashplayer">
    </embed>
  </object>

<!--   <div class="buttons">
    <button id="recordButton" class="btn btn-primary">Record</button>
    <button id="stopButton" class="btn btn-warning">Stop</button>
    <button id="playButton" class="btn">Play</button>
  </div> -->
</div>

<div class="footer">
  <%= link_to 'Back to list', clients_path, {class: 'bigBtn'} %>
</div>

app/views/clients/edit.html.erb
<div class="content-wrapper">

  <%= render 'form' %>

  <div class="table-footer">
    <%= link_to 'Back', clients_path, {class: 'bigBtn new-client'} %>
  </div>

</div>

app/views/clients/index.html.erb
<div class="content-wrapper">
  <p id="notice"><%= notice %></p>

  <table class='table clients'>
    <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th colspan="3">Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @clients.each do |client| %>
        <tr> 
          <td><%= (client.first_name || "") + " " + (client.last_name || "") %></td>
          <td><%= client.email %></td>
          <td>
          <%= link_to 'Record video!', camcorder_client_path(client), {class: 'bigBtn'} %>
          <%= link_to 'Edit', edit_client_path(client), {class: 'bigBtn'} %>
          <%= link_to 'Delete', client, method: :delete, data: { confirm: 'Are you sure?' }, class: 'bigBtn' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div class="table-footer">
    <%= link_to 'New Client', new_client_path, {class: 'bigBtn new-client'} %>
    <%= paginate @clients %>
  </div>
</div>

<br>

app/views/clients/new.html.erb
<div class="content-wrapper">

  <div class="notice">* These fields are mandatory</div>

  <%= render 'form' %>

  <div class="disclaimer">
    By submitting this form, I agree to receive communications, including emails, from
    <i>Cirque du Soleil</i> about news, events, offers, contests, other promotions, invitations and
    surveys regarding <i>Cirque du Soleil</i>, its affiliates, partners and One Drop's activities, services
    and products. You may unsubscribe or modify your preferences at any time. Please refer to
    our <a href="#">Privacy Policy</a> or <a href="#">contact us</a> for more details.
  </div>

  <div class="table-footer">
    <%= link_to 'Back to list', clients_path, {class: 'bigBtn'} %>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Camcorder</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller_name %> <%= action_name %>">

<div class="container">
  <%= yield %>
</div>

<div class="site-footer">Copyright ©2015 Cirque du soleil. All Rights Reserved.</div>

</body>
</html>